import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/navbar";
import BottomNav from "@/components/bottomNav";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });
import { getUserFromDatabase } from "@/services/getUserFromDatabase";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUserFromDatabase();
  console.log(user);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
            <Header
              user={user}
              name={user?.nama}
              avatar_url={user?.email}
            />
          <BottomNav />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
